using System.ComponentModel.DataAnnotations;

namespace TaskViewerApis.Models
{
    public class Pa
    {
        [Key]
        public string PlmId { get; set; }
        public string ProjectName { get; set; }
        public string LoadedCurrValue { get; set; }
        public string LoadedIntmValue { get; set; }
        public string LoadedRefValue { get; set; }
        public string LockFlag { get; set; }
        public string LockDate { get; set; }
        public string LockUser { get; set; }
        public string DecPsa { get; set; }
        public string State { get; set; }
        public string TechnicalAttributesCurrValue { get; set; }
        public string TechnicalAttributesIntmValue { get; set; }
        public string TechnicalAttributesRefValue { get; set; }
        public string FamilleCurrValue { get; set; }
        public string FamilleIntmValue { get; set; }
        public string FamilleRefValue { get; set; }
        public string Owner { get; set; }
        public string Mcid { get; set; }
        public string Np { get; set; }
        public string PdefMonitored { get; set; }
        public string PdefSupplierDate { get; set; }
        public string PdefCommonDate { get; set; }
        public string Pdef3DExist { get; set; }
        public string PdefLeader { get; set; }
        public string PdefIsCarryOver { get; set; }
        public string PdefValidateDate { get; set; }
        public string PdefValidate { get; set; }
        public string PreaMonitored { get; set; }
        public string PreaSupplierDate { get; set; }
        public string PreaCommonDate { get; set; }
        public string Prea3DExist { get; set; }
        public string PreaLeader { get; set; }
        public string PreaIsCarryOver { get; set; }
        public string PreaValidateDate { get; set; }
        public string PreaValidate { get; set; }
        public string PdefPreaComments { get; set; }
        public string Exc { get; set; }
        public string WorkingPackage { get; set; }
        public string AffectedPerson { get; set; }
        public string Ecr { get; set; }
        public string LaCurrValue { get; set; }
        public string LaIntmValue { get; set; }
        public string LaRefValue { get; set; }
        public string CodeAchat { get; set; }
        public string EffectivityOrValue { get; set; }
        public string EffectivityUserValue { get; set; }
        public string EffectivitySimilarTo { get; set; }
        public string VarianceSchemaOrValue { get; set; }
        public string VarianceSchemaUserValue { get; set; }
        public decimal MassObjectiveCurrValue { get; set; }
        public decimal MassObjectiveIntmValue { get; set; }
        public decimal MassObjectiveRefValue { get; set; }
        public string EC4Distribution { get; set; }
        public string EC4Revision { get; set; }
        public string CNXCurrValue { get; set; }
        public string CNXIntmValue { get; set; }
        public string CNXRefValue { get; set; }
        public string PDEFCurrValue { get; set; }
        public string PDEFIntmValue { get; set; }
        public string PDEFRefValue { get; set; }
        public string LINKSCurrValue { get; set; }
        public string LINKSIntmValue { get; set; }
        public string LINKSRefValue { get; set; }
        public string ObjectId { get; set; }
        public string PLMComments { get; set; }
        public string Comments { get; set; }
        public string CreationDate { get; set; }
        public string ValidationDate { get; set; }
        public string RequestedBy { get; set; }
        public string CreationValidation { get; set; }
        public string AvailabilityDate { get; set; }
        public string NewApplicability1 { get; set; }
        public string NewApplicability2 { get; set; }
        public string MandatoryMatrixORValue { get; set; }
        public string MandatoryMatrixUserValue { get; set; }
        public string MatrixState { get; set; }
        public string StateOfLinkLowInterchange { get; set; }
        public string ASolutionOfInterchangeExists { get; set; }
        public string MCMatrixName { get; set; }
        public int Flag { get; set; }
        public string ErrorSCurrValue { get; set; }
        public string ErrorSIntmValue { get; set; }
        public string ErrorSRefValue { get; set; }
        public string Tasks { get; set; }
        public string Selected { get; set; }
        public string LastModifDate { get; set; }
        public string BelongsToPCurrValue { get; set; }
        public string BelongsToPIntmValue { get; set; }
        public string BelongsToPRefValue { get; set; }
        public string MissingPDEFInPCurrValue { get; set; }
        public string MissingPDEFInPIntmValue { get; set; }
        public string MissingPDEFInPRefValue { get; set; }
        public string ToKill { get; set; }
        public string StateSCurrValue { get; set; }
        public string StateSIntmValue { get; set; }
        public string StateSRefValue { get; set; }
        public string EC4DistributionSCurrValue { get; set; }
        public string EC4DistributionSIntmValue { get; set; }
        public string EC4DistributionSRefValue { get; set; }
        public string HighestRevision { get; set; }
        public string CreatedAt { get; set; }
        public string LastModifAt { get; set; }
        public string ConfigurationContext { get; set; }
        public string KPICalled { get; set; }
        public string WaitApp { get; set; }
        public string LastTouch { get; set; }
        public string EC4DistributionIsNew { get; set; }
        public string ErrorDesc { get; set; }
        public string ChildCNXCurrValue { get; set; }
        public string ChildCNXIntmValue { get; set; }
        public string ChildCNXRefValue { get; set; }
        public string ChildPDEFCurrValue { get; set; }
        public string ChildPDEFIntmValue { get; set; }
        public string ChildPDEFRefValue { get; set; }
        public string ErrorDescSCurrValue { get; set; }
        public string ErrorDescSIntmValue { get; set; }
        public string ErrorDescSRefValue { get; set; }
        public string FatherNP { get; set; }
        public string LAIDSCurrValue { get; set; }
        public string LAIDSIntmValue { get; set; }
        public string LAIDSRefValue { get; set; }
        public string PartialGroup { get; set; }
        public string UseCaseAssociatedTo { get; set; }
        public string TaskLink { get; set; }
        public string CreatedBy { get; set; }
        public string EC4DistributionPrevious { get; set; }
        public byte[] EffectivityCur { get; set; }
        public string DNAErrors { get; set; }
        public byte[] DNAErrorDesc { get; set; }
        public string ProposedUseCase { get; set; }
        public string EffectivityIsUpdated { get; set; }
        public string IsArchived { get; set; }
        public string EC4Scripting { get; set; }
        public string ColorRefs { get; set; }
        public string LatestEvent { get; set; }
        public string EventType { get; set; }
        public string PreviousEffectivity { get; set; }
        public string CancelledAt { get; set; }
        public string RequestedRefs { get; set; }
    }
}
