// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskViewerApis.Data;

#nullable disable

namespace TaskViewerApis.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240523112225_duplicatenps")]
    partial class duplicatenps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskViewer.Models.Project", b =>
                {
                    b.Property<string>("PlmId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssociatedBoms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BomCommissionInCharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BomOperators")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brothers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BrothersSyncDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CnxBasedOnCnx")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CnxCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CnxCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CnxListBox")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnxRobotDirectory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnxRobotEnabled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnxRobotFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommonCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompodiagUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContexts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Continent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CountOfUndefinedGenomes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DbVersion")
                        .HasColumnType("int");

                    b.Property<string>("DefaultApplicability1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultApplicability2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultExc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultWpk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DieselPwtCompatibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DisablePopupMess")
                        .HasColumnType("bit");

                    b.Property<decimal?>("DnaBumpCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DnaBumpCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DnaBumpHoleCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DnaBumpHoleCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DnaCombineMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DnaErrorsReportMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DnaHealthyCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DnaHealthyCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DnaHoleCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DnaHoleCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DnaLastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DnaOtherCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DnaOtherCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EcoCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EcoCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EcoDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EcoProjectPattern1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcoProjectPattern2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcoProjectPattern3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcrDrivenCommissions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElectricPwtCompatibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngOperators")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrLogWrite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExcDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExcKw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedConfs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FastenersManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GasolinePwtCompatibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HpContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HybridPwtCompatibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsEcrDrivenBom")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFullyEcrDriven")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOrphan")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUsingBomWorkshop")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUsingCnxWorkshop")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUsingDnaWorkshop")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUsingTpcWorkshop")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LACount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LaCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LaDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLoadedBomDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastTouch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastValidBomDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LfFixMon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LfFixSd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadedBomDataCurrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadedBomDataIntmValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadedBomDataRefValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LockDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LockFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MilestonesFileDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NominalCnxNumber")
                        .HasColumnType("int");

                    b.Property<int?>("NpCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("NpCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("NpgDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("OfflineAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OfflineDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtherExc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PConfCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("PConfCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PConfs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PDefCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("PDefCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PDefListDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PDefPreAgendaDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PaCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("PaCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaOfficializeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PageGenericGDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Partnership")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PortfolioDateCmag")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PortfolioDateDchmExt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PortfolioDateDchmInt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PortfolioDateDsee")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PortfolioDateIcdv")
                        .HasColumnType("datetime2");

                    b.Property<string>("PortfolioPathCmag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioPathDchmExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioPathDchmInt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioPathDsee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioPathIcdv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerBom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PowerBomAssDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PowerBomModDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PowerBomProdDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PreaCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("PreaCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PrfCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrfCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrfEpsilon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PrfProgram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrfProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrfStdYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProjCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectTypePLM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Projects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefExc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RobotComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryOwnership")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SilSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SilType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmartMeasures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Sop")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ToKill")
                        .HasColumnType("bit");

                    b.Property<string>("TradeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwinProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf1Is100Pc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf2Is100Pc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf3Is100Pc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf4Is100Pc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf5Is100Pc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlmId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TaskViewer.Models.Task", b =>
                {
                    b.Property<string>("PlmId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AffectedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AlmostCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AlmostCompletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CarriedDecPsa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarrierDecPsa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CicxSide")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnxProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DReadEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DecPlmId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DecPsa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcoPlmId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcrPlmId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FeedbackDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterfaceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsEmbedded")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFromFastenerWorkshop")
                        .HasColumnType("bit");

                    b.Property<string>("JustificationComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastTouch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListOfTasks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocalIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LockFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ManagerCompletionApproved")
                        .HasColumnType("bit");

                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectPlmId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OddSituationReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousPlmId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RcdFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RcdName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RecentlyModifiedByRobot")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedCicx")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedBomCommission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedBusiness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SendMail")
                        .HasColumnType("bit");

                    b.Property<string>("TaskJustification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ToKill")
                        .HasColumnType("bit");

                    b.Property<string>("TypeOfTask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPlmId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workshop")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlmId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TaskViewer.Models.TaskDetail", b =>
                {
                    b.Property<string>("PlmId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("Cancelled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FatherTaskName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldToModify")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KValueOrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KValueUserValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastTouch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocalIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LockFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModificationDetailBoolHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ModificationDetailBoolOrValue")
                        .HasColumnType("bit");

                    b.Property<string>("ModificationDetailDateHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDetailDateOrValue")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificationDetailDateSonOf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModificationDetailRealHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModificationDetailRealOrValue")
                        .HasColumnType("int");

                    b.Property<string>("ObjectIdToUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalValueString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Par1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Par2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Par3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Par4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Par5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ToKill")
                        .HasColumnType("bit");

                    b.Property<int?>("TypeOfData")
                        .HasColumnType("int");

                    b.Property<string>("TypeOfTask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Validated")
                        .HasColumnType("bit");

                    b.Property<bool?>("XxMdbUserv")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("XxMddUserv")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("XxMdiH")
                        .HasColumnType("bit");

                    b.Property<int?>("XxMdiOrv")
                        .HasColumnType("int");

                    b.Property<int?>("XxMdiUserv")
                        .HasColumnType("int");

                    b.Property<int?>("XxMdrUserv")
                        .HasColumnType("int");

                    b.Property<string>("XxMdsH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XxMdsOrv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XxMdsUserv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlmId");

                    b.ToTable("TaskDetails");
                });

            modelBuilder.Entity("TaskViewer.Models.User", b =>
                {
                    b.Property<string>("PlmId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("AutoSaveActivated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("DisablePopupMess")
                        .HasColumnType("bit");

                    b.Property<bool?>("DisableProjectInfoPopup")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Homepage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsKeyUser")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastConnection")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastTouch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LockDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("LockFlag")
                        .HasColumnType("bit");

                    b.Property<string>("LockUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainActivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MyHighCardinal")
                        .HasColumnType("int");

                    b.Property<int?>("MyLowCardinal")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfConnexions")
                        .HasColumnType("int");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OldLaFilter")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrefBomComByProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PreloadingDelayDays")
                        .HasColumnType("int");

                    b.Property<bool?>("PrfConfidential")
                        .HasColumnType("bit");

                    b.Property<string>("Proj1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proj10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proj2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proj3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proj4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proj5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proj6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proj7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proj8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proj9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PwtSqlLoader")
                        .HasColumnType("bit");

                    b.Property<string>("SelectedVoice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkipDbChoice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SoundOption")
                        .HasColumnType("bit");

                    b.Property<bool?>("StyleConfidential")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SubscribedSince")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ToKill")
                        .HasColumnType("bit");

                    b.Property<string>("VisitedProjects")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlmId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TaskViewerApis.Models.Error", b =>
                {
                    b.Property<string>("PlmId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Actors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contributors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectiveAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastTouch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedObject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tokill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UseAsKpiFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workshop")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlmId");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("TaskViewerApis.Models.Message", b =>
                {
                    b.Property<string>("PlmId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastTouch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LockDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LockFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageDestination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTxt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObjectPlmid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PictureCount")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReadBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ToKill")
                        .HasColumnType("bit");

                    b.Property<int?>("TweetLenMax")
                        .HasColumnType("int");

                    b.Property<string>("WrittenBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlmId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TaskViewerApis.Models.Np", b =>
                {
                    b.Property<string>("BaseVeh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseVehicleInNp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelongstopcConfCurrvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelongstopcConfIntmvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelongstopcConfRefvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CancelledAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChildpaCurrvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChildpaIntmvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChildpaRefvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassificationOrvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassificationUservalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreationValidation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Decpsa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DnaBumpsCount")
                        .HasColumnType("int");

                    b.Property<int?>("DnaCombinationsCount")
                        .HasColumnType("int");

                    b.Property<string>("DnaErrors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DnaHolesCount")
                        .HasColumnType("int");

                    b.Property<string>("DnaIsUptodate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DnaMaxCombines")
                        .HasColumnType("int");

                    b.Property<int?>("DnaOtherErrorsCount")
                        .HasColumnType("int");

                    b.Property<string>("DnaTaskAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DnaTaskDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DnaTaskRcd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DnaTaskRcdFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffRestriction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffRestrictionIsUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrordescCurrvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrordescIntmvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrordescRefvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorsCurrvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorsIntmvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorsRefvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactoryperimeterOrvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactoryperimeterUservalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Flag")
                        .HasColumnType("int");

                    b.Property<string>("ImplementationArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncludedCurrvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncludedIntmvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncludedRefvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsDnaCombinationsFull")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kb01Pconfs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KpiCalled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastTouch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadedCurrvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadedIntmvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadedRefvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleInNp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleTypeInNp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NbpaCurrvalue")
                        .HasColumnType("int");

                    b.Property<int?>("NbpaIntmvalue")
                        .HasColumnType("int");

                    b.Property<int?>("NbpaRefvalue")
                        .HasColumnType("int");

                    b.Property<string>("NextnpByDecpsa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaLinks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortraitRobot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowertrainInNp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PresentinCurrvalue")
                        .HasColumnType("int");

                    b.Property<int?>("PresentinIntmvalue")
                        .HasColumnType("int");

                    b.Property<int?>("PresentinRefvalue")
                        .HasColumnType("int");

                    b.Property<string>("PreviousRestriction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrfMetierSpec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tasks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tokill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypenpOrvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypenpUservalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WinAttachement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XxErCv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XxErIv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XxErRv")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Nps");
                });

            modelBuilder.Entity("TaskViewerApis.Models.Pa", b =>
                {
                    b.Property<string>("PlmId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ASolutionOfInterchangeExists")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AffectedPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvailabilityDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelongsToPCurrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelongsToPIntmValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelongsToPRefValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNXCurrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNXIntmValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNXRefValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CancelledAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChildCNXCurrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChildCNXIntmValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChildCNXRefValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChildPDEFCurrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChildPDEFIntmValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChildPDEFRefValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeAchat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorRefs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreationValidation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("DNAErrorDesc")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("DNAErrors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DecPsa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EC4Distribution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EC4DistributionIsNew")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EC4DistributionPrevious")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EC4DistributionSCurrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EC4DistributionSIntmValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EC4DistributionSRefValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EC4Revision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EC4Scripting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ecr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("EffectivityCur")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("EffectivityIsUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectivityOrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectivitySimilarTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectivityUserValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorDescSCurrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorDescSIntmValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorDescSRefValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorSCurrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorSIntmValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorSRefValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilleCurrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilleIntmValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilleRefValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherNP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Flag")
                        .HasColumnType("int");

                    b.Property<string>("HighestRevision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsArchived")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KPICalled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LAIDSCurrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LAIDSIntmValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LAIDSRefValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LINKSCurrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LINKSIntmValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LINKSRefValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LaCurrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LaIntmValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LaRefValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastTouch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadedCurrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadedIntmValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadedRefValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MCMatrixName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MandatoryMatrixORValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MandatoryMatrixUserValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MassObjectiveCurrValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MassObjectiveIntmValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MassObjectiveRefValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MatrixState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mcid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissingPDEFInPCurrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissingPDEFInPIntmValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissingPDEFInPRefValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewApplicability1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewApplicability2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Np")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PDEFCurrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PDEFIntmValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PDEFRefValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLMComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartialGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pdef3DExist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdefCommonDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdefIsCarryOver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdefLeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdefMonitored")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdefPreaComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdefSupplierDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdefValidate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdefValidateDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prea3DExist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreaCommonDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreaIsCarryOver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreaLeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreaMonitored")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreaSupplierDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreaValidate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreaValidateDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousEffectivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedUseCase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedRefs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Selected")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateOfLinkLowInterchange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateSCurrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateSIntmValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateSRefValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tasks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalAttributesCurrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalAttributesIntmValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalAttributesRefValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToKill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UseCaseAssociatedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VarianceSchemaOrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VarianceSchemaUserValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaitApp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingPackage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlmId");

                    b.ToTable("Pas");
                });
#pragma warning restore 612, 618
        }
    }
}
