using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TaskViewerApis.Migrations
{
    /// <inheritdoc />
    public partial class firstMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Projects",
                columns: table => new
                {
                    PlmId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    ProjectName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ProductLine = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Brand = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Brothers = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TwinProject = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GasolinePwtCompatibility = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DieselPwtCompatibility = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ElectricPwtCompatibility = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HybridPwtCompatibility = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SilType = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SilSize = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AssociatedBoms = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DbVersion = table.Column<int>(type: "int", nullable: false),
                    CreationDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ProjectType = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Platform = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Continent = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    NpCount = table.Column<int>(type: "int", nullable: false),
                    PaCount = table.Column<int>(type: "int", nullable: false),
                    PDefCount = table.Column<int>(type: "int", nullable: false),
                    PreaCount = table.Column<int>(type: "int", nullable: false),
                    CnxCount = table.Column<int>(type: "int", nullable: false),
                    PrfCount = table.Column<int>(type: "int", nullable: false),
                    PConfCount = table.Column<int>(type: "int", nullable: false),
                    PowerBom = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Sop = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ProjCreationDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    PowerBomAssDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    PowerBomProdDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    LaDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    EcoDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    NpgDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    BrothersSyncDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    PageGenericGDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    PDefPreAgendaDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    MilestonesFileDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ExcDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    PDefListDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    DefaultApplicability1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DefaultApplicability2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DefaultExc = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DefaultWpk = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DefaultUser = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RefExc = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExcKw = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    OtherExc = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    NominalCnxNumber = table.Column<int>(type: "int", nullable: false),
                    PrfProgram = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PrfProject = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PortfolioPathDsee = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PortfolioPathDchmInt = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PortfolioPathDchmExt = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PortfolioPathIcdv = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PortfolioPathCmag = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PortfolioDateDsee = table.Column<DateTime>(type: "datetime2", nullable: false),
                    PortfolioDateDchmInt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    PortfolioDateDchmExt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    PortfolioDateIcdv = table.Column<DateTime>(type: "datetime2", nullable: false),
                    PortfolioDateCmag = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ErrLogWrite = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CnxBasedOnCnx = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PrfEpsilon = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    PrfStdYear = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CompodiagUpdated = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Comments = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Picture = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CnxListBox = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Projects = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExpectedConfs = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PConfs = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SmartMeasures = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ToKill = table.Column<bool>(type: "bit", nullable: false),
                    EcoCount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    LACount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    LastUpdate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    LastUpdateBy = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PowerBomModDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ConfigurationContext = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BomOperators = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EngOperators = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ConfigurationContext1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ConfigurationContext2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ConfigurationContext3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ConfigurationContext4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ConfigurationContext5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ConfigurationContexts = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Vrf1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    IsEcrDrivenBom = table.Column<bool>(type: "bit", nullable: false),
                    Vrf1Is100Pc = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Vrf2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Vrf2Is100Pc = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Vrf3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Vrf3Is100Pc = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Vrf4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Vrf4Is100Pc = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Vrf5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Vrf5Is100Pc = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BomCommissionInCharge = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LastTouch = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ConfigurationContext6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ConfigurationContext7 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ConfigurationContext8 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    OfflineAvailable = table.Column<bool>(type: "bit", nullable: false),
                    OfflineDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    IsOrphan = table.Column<bool>(type: "bit", nullable: false),
                    LastValidBomDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    SecondaryOwnership = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DisablePopupMess = table.Column<bool>(type: "bit", nullable: false),
                    PaOfficializeDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    LoadedBomDataCurrValue = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LoadedBomDataIntmValue = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LoadedBomDataRefValue = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LastLoadedBomDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    EcrDrivenCommissions = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    IsFullyEcrDriven = table.Column<bool>(type: "bit", nullable: false),
                    TradeName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CnxRobotDirectory = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CnxRobotEnabled = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CnxRobotFileName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EcoProjectPattern1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EcoProjectPattern2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EcoProjectPattern3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RobotComment = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LockDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    LockFlag = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LockUser = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MarketingName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Partnership = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ProjectTypePLM = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FastenersManager = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CountOfUndefinedGenomes = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    IsUsingBomWorkshop = table.Column<bool>(type: "bit", nullable: false),
                    IsUsingCnxWorkshop = table.Column<bool>(type: "bit", nullable: false),
                    IsUsingTpcWorkshop = table.Column<bool>(type: "bit", nullable: false),
                    IsUsingDnaWorkshop = table.Column<bool>(type: "bit", nullable: false),
                    NpCountPrev = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    PaCountPrev = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    PDefCountPrev = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    PreaCountPrev = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    CnxCountPrev = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    PrfCountPrev = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    PConfCountPrev = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    LaCountPrev = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    DnaCombineMax = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    DnaErrorsReportMax = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    DnaBumpCount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    DnaHoleCount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    DnaBumpHoleCount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    DnaOtherCount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    DnaHealthyCount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    DnaBumpCountPrev = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    DnaHoleCountPrev = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    DnaBumpHoleCountPrev = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    DnaOtherCountPrev = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    DnaHealthyCountPrev = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    DnaLastUpdate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    EcoCountPrev = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    CommonCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LfFixMon = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LfFixSd = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HpContext = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CancelledAt = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Projects", x => x.PlmId);
                });

            migrationBuilder.CreateTable(
                name: "TaskDetails",
                columns: table => new
                {
                    PlmId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    ProjectName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LocalIndex = table.Column<int>(type: "int", nullable: false),
                    LockFlag = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LockDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    LockUser = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FatherTaskName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TypeOfTask = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TypeOfData = table.Column<int>(type: "int", nullable: false),
                    FieldToModify = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XxMdsOrv = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XxMdsUserv = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XxMdsH = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ModificationDetailRealOrValue = table.Column<int>(type: "int", nullable: false),
                    XxMdrUserv = table.Column<int>(type: "int", nullable: false),
                    ModificationDetailRealHistory = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    XxMdiOrv = table.Column<int>(type: "int", nullable: false),
                    XxMdiUserv = table.Column<int>(type: "int", nullable: false),
                    XxMdiH = table.Column<bool>(type: "bit", nullable: false),
                    ModificationDetailBoolOrValue = table.Column<bool>(type: "bit", nullable: false),
                    XxMdbUserv = table.Column<bool>(type: "bit", nullable: false),
                    ModificationDetailBoolHistory = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ModificationDetailDateSonOf = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ModificationDetailDateOrValue = table.Column<DateTime>(type: "datetime2", nullable: false),
                    XxMddUserv = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModificationDetailDateHistory = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RequestedBy = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RequestedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Validated = table.Column<bool>(type: "bit", nullable: false),
                    Completed = table.Column<bool>(type: "bit", nullable: false),
                    OriginalValueString = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ToKill = table.Column<bool>(type: "bit", nullable: false),
                    ObjectIdToUse = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LastTouch = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KValueOrValue = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KValueUserValue = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Comments = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CompletedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CompletedBy = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Par1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Par2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Par3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Par4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Par5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Cancelled = table.Column<bool>(type: "bit", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CancelledAt = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TaskDetails", x => x.PlmId);
                });

            migrationBuilder.CreateTable(
                name: "Tasks",
                columns: table => new
                {
                    PlmId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    ProjectName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LocalIndex = table.Column<int>(type: "int", nullable: false),
                    LockFlag = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LockDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    LockUser = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ProductLine = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Workshop = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ValidatedBy = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ValidatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ObjectType = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TypeOfTask = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ValidationStatus = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Comments = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ListOfTasks = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    History = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EcrPlmId = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ObjectPlmId = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PreviousPlmId = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FeedbackDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    RcdFeedback = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RcdName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TaskJustification = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    JustificationComment = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ToKill = table.Column<bool>(type: "bit", nullable: false),
                    DecPsa = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AffectedTo = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SelectedBusiness = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SelectedBomCommission = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DecPlmId = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LastTouch = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CompletedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    NewProductId = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MessageId = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CarriedDecPsa = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CarrierDecPsa = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CnxProjectName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DReadEvent = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    InterfaceId = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    IsArchived = table.Column<bool>(type: "bit", nullable: false),
                    IsEmbedded = table.Column<bool>(type: "bit", nullable: false),
                    CompletedBy = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ManagerCompletionApproved = table.Column<bool>(type: "bit", nullable: false),
                    RecentlyModifiedByRobot = table.Column<bool>(type: "bit", nullable: false),
                    UserPlmId = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CicxSide = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EcoPlmId = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RejectedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    RejectedBy = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RelatedCicx = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SendMail = table.Column<bool>(type: "bit", nullable: false),
                    AlmostCompletedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    AlmostCompletedBy = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    OddSituationReport = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CancelledAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    IsFromFastenerWorkshop = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Tasks", x => x.PlmId);
                });

            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    PlmId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    FirstName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LastName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Occupation = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PrfConfidential = table.Column<bool>(type: "bit", nullable: false),
                    StyleConfidential = table.Column<bool>(type: "bit", nullable: false),
                    Proj1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Proj2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Proj3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Proj4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Proj5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Proj6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Proj7 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Proj8 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Proj9 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Proj10 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    NumberOfConnexions = table.Column<int>(type: "int", nullable: false),
                    SubscribedSince = table.Column<DateTime>(type: "datetime2", nullable: false),
                    LastConnection = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Picture = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Sex = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Homepage = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SoundOption = table.Column<bool>(type: "bit", nullable: false),
                    PreferredLanguage = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ToKill = table.Column<bool>(type: "bit", nullable: false),
                    VisitedProjects = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LastTouch = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AddedBy = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MainActivity = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PwtSqlLoader = table.Column<bool>(type: "bit", nullable: false),
                    PreloadingDelayDays = table.Column<int>(type: "int", nullable: false),
                    DisablePopupMess = table.Column<bool>(type: "bit", nullable: false),
                    Service = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PrefBomComByProject = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    OldLaFilter = table.Column<int>(type: "int", nullable: false),
                    SelectedVoice = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SkipDbChoice = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Company = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MyHighCardinal = table.Column<int>(type: "int", nullable: false),
                    MyLowCardinal = table.Column<int>(type: "int", nullable: false),
                    AutoSaveActivated = table.Column<bool>(type: "bit", nullable: false),
                    LockDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    LockFlag = table.Column<bool>(type: "bit", nullable: false),
                    LockUser = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    IsKeyUser = table.Column<bool>(type: "bit", nullable: false),
                    DisableProjectInfoPopup = table.Column<bool>(type: "bit", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CancelledAt = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.PlmId);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Projects");

            migrationBuilder.DropTable(
                name: "TaskDetails");

            migrationBuilder.DropTable(
                name: "Tasks");

            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
