// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskViewerApis.Data;

#nullable disable

namespace TaskViewerApis.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskViewer.Models.Project", b =>
                {
                    b.Property<string>("PlmId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssociatedBoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BomCommissionInCharge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BomOperators")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brothers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BrothersSyncDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CnxBasedOnCnx")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CnxCount")
                        .HasColumnType("int");

                    b.Property<decimal>("CnxCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CnxListBox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnxRobotDirectory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnxRobotEnabled")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnxRobotFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommonCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompodiagUpdated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContext8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationContexts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CountOfUndefinedGenomes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DbVersion")
                        .HasColumnType("int");

                    b.Property<string>("DefaultApplicability1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultApplicability2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultExc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultWpk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DieselPwtCompatibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisablePopupMess")
                        .HasColumnType("bit");

                    b.Property<decimal>("DnaBumpCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DnaBumpCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DnaBumpHoleCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DnaBumpHoleCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DnaCombineMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DnaErrorsReportMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DnaHealthyCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DnaHealthyCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DnaHoleCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DnaHoleCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DnaLastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DnaOtherCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DnaOtherCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EcoCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EcoCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EcoDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EcoProjectPattern1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcoProjectPattern2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcoProjectPattern3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcrDrivenCommissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElectricPwtCompatibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngOperators")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrLogWrite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExcDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExcKw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedConfs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FastenersManager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GasolinePwtCompatibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HpContext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HybridPwtCompatibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEcrDrivenBom")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFullyEcrDriven")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOrphan")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsingBomWorkshop")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsingCnxWorkshop")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsingDnaWorkshop")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsingTpcWorkshop")
                        .HasColumnType("bit");

                    b.Property<decimal>("LACount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LaCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LaDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastLoadedBomDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastTouch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastValidBomDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LfFixMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LfFixSd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadedBomDataCurrValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadedBomDataIntmValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadedBomDataRefValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LockDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LockFlag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MilestonesFileDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NominalCnxNumber")
                        .HasColumnType("int");

                    b.Property<int>("NpCount")
                        .HasColumnType("int");

                    b.Property<decimal>("NpCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NpgDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OfflineAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OfflineDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtherExc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PConfCount")
                        .HasColumnType("int");

                    b.Property<decimal>("PConfCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PConfs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PDefCount")
                        .HasColumnType("int");

                    b.Property<decimal>("PDefCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PDefListDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PDefPreAgendaDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaCount")
                        .HasColumnType("int");

                    b.Property<decimal>("PaCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaOfficializeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PageGenericGDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Partnership")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PortfolioDateCmag")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PortfolioDateDchmExt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PortfolioDateDchmInt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PortfolioDateDsee")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PortfolioDateIcdv")
                        .HasColumnType("datetime2");

                    b.Property<string>("PortfolioPathCmag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioPathDchmExt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioPathDchmInt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioPathDsee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioPathIcdv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerBom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PowerBomAssDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PowerBomModDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PowerBomProdDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PreaCount")
                        .HasColumnType("int");

                    b.Property<decimal>("PreaCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrfCount")
                        .HasColumnType("int");

                    b.Property<decimal>("PrfCountPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrfEpsilon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PrfProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrfProject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrfStdYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProjCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectTypePLM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Projects")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefExc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RobotComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryOwnership")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SilSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SilType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmartMeasures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Sop")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ToKill")
                        .HasColumnType("bit");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwinProject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf1Is100Pc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf2Is100Pc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf3Is100Pc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf4Is100Pc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrf5Is100Pc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlmId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TaskViewer.Models.Task", b =>
                {
                    b.Property<string>("PlmId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AffectedTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AlmostCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AlmostCompletedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CarriedDecPsa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarrierDecPsa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CicxSide")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnxProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DReadEvent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DecPlmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DecPsa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcoPlmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcrPlmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FeedbackDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterfaceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmbedded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFromFastenerWorkshop")
                        .HasColumnType("bit");

                    b.Property<string>("JustificationComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastTouch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListOfTasks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocalIndex")
                        .HasColumnType("int");

                    b.Property<DateTime>("LockDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LockFlag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ManagerCompletionApproved")
                        .HasColumnType("bit");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectPlmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OddSituationReport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousPlmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RcdFeedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RcdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RecentlyModifiedByRobot")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedCicx")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedBomCommission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedBusiness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SendMail")
                        .HasColumnType("bit");

                    b.Property<string>("TaskJustification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ToKill")
                        .HasColumnType("bit");

                    b.Property<string>("TypeOfTask")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPlmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workshop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlmId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TaskViewer.Models.TaskDetail", b =>
                {
                    b.Property<string>("PlmId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FatherTaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldToModify")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KValueOrValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KValueUserValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastTouch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocalIndex")
                        .HasColumnType("int");

                    b.Property<DateTime>("LockDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LockFlag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModificationDetailBoolHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ModificationDetailBoolOrValue")
                        .HasColumnType("bit");

                    b.Property<string>("ModificationDetailDateHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificationDetailDateOrValue")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificationDetailDateSonOf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModificationDetailRealHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModificationDetailRealOrValue")
                        .HasColumnType("int");

                    b.Property<string>("ObjectIdToUse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalValueString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Par1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Par2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Par3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Par4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Par5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ToKill")
                        .HasColumnType("bit");

                    b.Property<int>("TypeOfData")
                        .HasColumnType("int");

                    b.Property<string>("TypeOfTask")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Validated")
                        .HasColumnType("bit");

                    b.Property<bool>("XxMdbUserv")
                        .HasColumnType("bit");

                    b.Property<DateTime>("XxMddUserv")
                        .HasColumnType("datetime2");

                    b.Property<bool>("XxMdiH")
                        .HasColumnType("bit");

                    b.Property<int>("XxMdiOrv")
                        .HasColumnType("int");

                    b.Property<int>("XxMdiUserv")
                        .HasColumnType("int");

                    b.Property<int>("XxMdrUserv")
                        .HasColumnType("int");

                    b.Property<string>("XxMdsH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XxMdsOrv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XxMdsUserv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlmId");

                    b.ToTable("TaskDetails");
                });

            modelBuilder.Entity("TaskViewer.Models.User", b =>
                {
                    b.Property<string>("PlmId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AutoSaveActivated")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DisablePopupMess")
                        .HasColumnType("bit");

                    b.Property<bool>("DisableProjectInfoPopup")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Homepage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsKeyUser")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastConnection")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastTouch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LockDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockFlag")
                        .HasColumnType("bit");

                    b.Property<string>("LockUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainActivity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MyHighCardinal")
                        .HasColumnType("int");

                    b.Property<int>("MyLowCardinal")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfConnexions")
                        .HasColumnType("int");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OldLaFilter")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrefBomComByProject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreloadingDelayDays")
                        .HasColumnType("int");

                    b.Property<bool>("PrfConfidential")
                        .HasColumnType("bit");

                    b.Property<string>("Proj1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proj10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proj2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proj3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proj4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proj5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proj6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proj7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proj8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proj9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PwtSqlLoader")
                        .HasColumnType("bit");

                    b.Property<string>("SelectedVoice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkipDbChoice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoundOption")
                        .HasColumnType("bit");

                    b.Property<bool>("StyleConfidential")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SubscribedSince")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ToKill")
                        .HasColumnType("bit");

                    b.Property<string>("VisitedProjects")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlmId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
